'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, RefreshCw, AlertTriangle, CheckCircle2, XCircle, ShieldAlert } from 'lucide-react';
import LoadingSpinner from '@/components/ui/LoadingSpinner';

export default function AccuracyAuditPage() {
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [recomputing, setRecomputing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchReport = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/admin/accuracy-audit');
      if (!res.ok) throw new Error('Failed to fetch accuracy audit data');
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setReport(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReport();
  }, []);

  const renderBadge = (status: string) => {
    if (status === 'PASS') return <span className="bg-green-500/20 text-green-400 border border-green-500/30 px-2 py-0.5 rounded text-sm font-bold flex items-center gap-1 w-fit"><CheckCircle2 className="w-4 h-4" /> PASS</span>;
    if (status === 'WARNING') return <span className="bg-yellow-500/20 text-yellow-400 border border-yellow-500/30 px-2 py-0.5 rounded text-sm font-bold flex items-center gap-1 w-fit"><AlertTriangle className="w-4 h-4" /> WARNING</span>;
    return <span className="bg-red-500/20 text-red-400 border border-red-500/30 px-2 py-0.5 rounded text-sm font-bold flex items-center gap-1 w-fit"><XCircle className="w-4 h-4" /> FAIL</span>;
  };

  return (
    <div className="min-h-screen bg-bg-primary text-text-primary p-6 font-sans">
      <div className="max-w-6xl mx-auto space-y-6">
        
        {/* Header Section */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border-custom pb-4">
          <div className="flex items-center gap-3">
            <Link href="/admin" className="p-2 bg-bg-secondary hover:bg-bg-card border border-border-custom rounded-lg transition-colors">
              <ArrowLeft className="w-5 h-5 text-text-secondary" />
            </Link>
            <div>
              <h1 className="text-2xl font-bold tracking-tight">Accuracy Audit & Overfitting Checks</h1>
              <p className="text-sm text-text-secondary mt-1">Strict validation of prediction claims, data integrity, and leakage prevention.</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button 
              onClick={fetchReport}
              className="flex items-center gap-2 bg-accent-blue/10 hover:bg-accent-blue/20 text-accent-blue px-4 py-2 rounded-lg border border-accent-blue/20 transition-all font-semibold"
              disabled={loading || recomputing}
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
              Run Audit
            </button>
          </div>
        </div>

        {error && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-4 flex gap-3 text-red-400">
            <ShieldAlert className="w-5 h-5 shrink-0" />
            <p className="text-sm">{error}</p>
          </div>
        )}

        {report && report.stalePredictionCount > 0 && (
          <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-4 flex flex-col sm:flex-row gap-4 justify-between sm:items-center text-yellow-400">
            <div className="flex gap-3">
              <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-yellow-300">Stale Analytics Data Detected</p>
                <p className="text-sm mt-1">There are {report.stalePredictionCount} predictions generated by an older prediction engine schema. Metrics may not reflect the latest accuracy improvements.</p>
                <p className="text-xs text-yellow-500 mt-2">Latest Engine Predictions: {report.latestPredictionCount}</p>
              </div>
            </div>
            <button
              onClick={async () => {
                if (!confirm(`Are you sure you want to recompute ${report.stalePredictionCount} predictions? This may take a while.`)) return;
                setRecomputing(true);
                setError(null);
                try {
                  const res = await fetch('/api/admin/recompute', { method: 'POST' });
                  if (!res.ok) throw new Error('Recompute request failed');
                  // After initiating, just refetch report every 5 seconds until stale count drops
                  const checkInterval = setInterval(async () => {
                     await fetchReport();
                  }, 5000);
                  // We'll leave it running, but clear interval when unmounted... just a simple auto-refresh
                  setTimeout(() => clearInterval(checkInterval), 60000);
                } catch (e: any) {
                  setError(e.message);
                  setRecomputing(false);
                }
              }}
              disabled={recomputing}
              className="whitespace-nowrap flex items-center justify-center gap-2 bg-yellow-500/20 hover:bg-yellow-500/30 text-yellow-300 px-4 py-2 rounded-lg border border-yellow-500/50 font-medium transition-colors"
            >
              {recomputing ? <><RefreshCw className="w-4 h-4 animate-spin" /> Recomputing...</> : 'Recompute With Latest Engine'}
            </button>
          </div>
        )}

        {loading && !report ? (
          <div className="h-64 flex items-center justify-center border border-border-custom rounded-xl bg-bg-secondary/50">
            <LoadingSpinner size="lg" />
          </div>
        ) : report ? (
          <div className="space-y-6">
            
            {/* Top Metrics Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-bg-card border border-border-custom rounded-lg p-4">
                <p className="text-xs text-text-secondary uppercase font-semibold">Total Verified</p>
                <p className="text-2xl font-bold mt-1">{report.totalVerified}</p>
              </div>
              <div className="bg-bg-card border border-border-custom rounded-lg p-4">
                <p className="text-xs text-text-secondary uppercase font-semibold">Overall Accuracy</p>
                <p className="text-2xl font-bold mt-1 text-accent-blue">{report.overallAccuracy}%</p>
              </div>
              <div className="bg-bg-card border border-border-custom rounded-lg p-4">
                <p className="text-xs text-text-secondary uppercase font-semibold">Tradeable Accuracy</p>
                <p className="text-2xl font-bold mt-1 text-premium-gold">{report.tradeableAccuracy}%</p>
              </div>
              <div className="bg-bg-card border border-border-custom rounded-lg p-4">
                <p className="text-xs text-text-secondary uppercase font-semibold">Mock Exclusions</p>
                <p className="text-2xl font-bold mt-1 text-red-400">{report.mockExclusionCount}</p>
              </div>
            </div>

            {/* Diagnostic Breakdown */}
            <div className="bg-bg-card border border-border-custom rounded-xl p-5 shadow-lg">
              <h3 className="font-bold text-lg mb-4 flex items-center justify-between">
                <span>Database Diagnostics</span>
                <button
                  onClick={async () => {
                    if (!confirm('Are you sure you want to delete all stale fake mock predictions from the database? This cannot be undone.')) return;
                    try {
                      const res = await fetch('/api/admin/clear-mock-data', { method: 'POST' });
                      if (!res.ok) throw new Error('Failed to clear mock data');
                      fetchReport();
                    } catch(e: any) {
                      alert(e.message);
                    }
                  }}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white text-[11px] font-semibold rounded-lg transition-all cursor-pointer"
                >
                  <XCircle className="w-3 h-3" />
                  Clear Stale Mock Data
                </button>
              </h3>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-6">
                <div>
                  <p className="text-sm text-text-secondary">Total Records in DB</p>
                  <p className="text-xl font-mono mt-1">{report.totalPredictionsCount}</p>
                </div>
                <div>
                  <p className="text-sm text-text-secondary">Latest Engine Records</p>
                  <p className="text-xl font-mono mt-1 text-accent-blue">{report.latestPredictionCount}</p>
                </div>
                <div>
                  <p className="text-sm text-text-secondary">Stale Engine Records</p>
                  <p className="text-xl font-mono mt-1 text-yellow-500">{report.stalePredictionCount}</p>
                </div>
                <div>
                  <p className="text-sm text-text-secondary">Audited & Verified</p>
                  <p className="text-xl font-mono mt-1 text-green-400">{report.totalVerified - report.mockExclusionCount}</p>
                </div>
              </div>
            </div>

            {/* Calibration Stats */}
            <div className="bg-bg-card border border-border-custom rounded-xl p-5 shadow-lg">
              <h3 className="font-bold text-lg mb-4">Calibration Health Metrics</h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                <div>
                  <p className="text-sm text-text-secondary">Avg Confidence (Correct)</p>
                  <p className="text-xl font-mono mt-1 text-green-400">{report.averageConfidenceCorrect}%</p>
                </div>
                <div>
                  <p className="text-sm text-text-secondary">Avg Confidence (Incorrect)</p>
                  <p className="text-xl font-mono mt-1 text-red-400">{report.averageConfidenceIncorrect}%</p>
                </div>
                <div>
                  <p className="text-sm text-text-secondary">High Confidence Error (ECE)</p>
                  <p className="text-xl font-mono mt-1 text-yellow-400">{report.calibrationError}% gap</p>
                </div>
              </div>
            </div>

            {/* Badges and Failures Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-bg-card border border-border-custom rounded-xl overflow-hidden shadow-lg">
                <div className="bg-bg-secondary p-4 border-b border-border-custom">
                  <h3 className="font-bold">Audit Badges</h3>
                </div>
                <div className="p-4 space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-text-secondary font-medium">Data Integrity</span>
                    {renderBadge(report.badges.dataIntegrity)}
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-text-secondary font-medium">No Future Leakage</span>
                    {renderBadge(report.badges.noLeakage)}
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-text-secondary font-medium">Calibration Health</span>
                    {renderBadge(report.badges.calibrationHealth)}
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-text-secondary font-medium">Sample Size Health</span>
                    {renderBadge(report.badges.sampleSizeHealth)}
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-text-secondary font-medium">Overfitting Risk</span>
                    {renderBadge(report.badges.overfittingRisk)}
                  </div>
                </div>
              </div>

              <div className="bg-bg-card border border-border-custom rounded-xl overflow-hidden shadow-lg flex flex-col">
                <div className="bg-bg-secondary p-4 border-b border-border-custom">
                  <h3 className="font-bold flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-red-400" /> Failure Reasons & Warnings</h3>
                </div>
                <div className="p-4 flex-1">
                  {report.failureReasons.length === 0 ? (
                    <div className="h-full flex flex-col items-center justify-center text-green-400 opacity-80 py-8">
                      <CheckCircle2 className="w-12 h-12 mb-3 opacity-50" />
                      <p className="font-medium text-center">System is completely healthy.<br/>No leakage or overfitting detected.</p>
                    </div>
                  ) : (
                    <ul className="list-disc pl-5 space-y-2 text-sm">
                      {report.failureReasons.map((reason: string, idx: number) => (
                        <li key={idx} className={reason.toLowerCase().includes('fail') || reason.toLowerCase().includes('critically') || reason.toLowerCase().includes('leakage') ? 'text-red-400' : 'text-yellow-400'}>
                          {reason}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
            </div>

          </div>
        ) : null}
      </div>
    </div>
  );
}
